//
//  BibleVerses.swift
//  Archangel Raphael
//
//  Created by Michael Ghebranious on 1/24/24.
//

import Foundation
var bibleVerses: [String] = [
    "John 3:16 - For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.",
    "Philippians 4:13 - I can do all things through him who strengthens me.",
    "Psalm 23:1 - The Lord is my shepherd; I shall not want.",
    "Jeremiah 29:11 - For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.",
    "Proverbs 1:7 - The fear of the Lord is the beginning of knowledge; fools despise wisdom and instruction.",
    "Romans 8:28 - And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
    "John 14:6 - I am the way, and the truth, and the life. No one comes to the Father except through me.",
    "Proverbs 3:5 - Trust in the Lord with all your heart, and do not lean on your own understanding.",
    "John 14:27 - Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid.",
    "Galatians 5:22-23 - But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness, and self-control.",
    "1 John 4:16 - And we have known and believed the love that God has for us. God is love, and he who abides in love abides in God, and God in him.",
    "Psalm 46:10 - Be still, and know that I am God. I will be exalted among the nations, I will be exalted in the earth!",
    "Ephesians 2:8 - For by grace you have been saved through faith. And this is not your own doing; it is the gift of God.",
    "Romans 12:12 - Rejoice in hope, be patient in tribulation, be constant in prayer.",
    "Matthew 5:9 - Blessed are the peacemakers, for they shall be called sons of God.",
    "Matthew 6:33 - But seek first the kingdom of God and his righteousness, and all these things will be added to you.",
    "Psalm 34:18 - The Lord is near to the brokenhearted and saves the crushed in spirit.",
    "Philippians 4:6 - Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.",
    "Matthew 5:16 - Let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven.",
    "Colossians 3:17 - And whatever you do, in word or deed, do everything in the name of the Lord Jesus, giving thanks to God the Father through him.",
    "John 16:33 - These things I have spoken to you, that in Me you may have peace. In the world you will have tribulation; but be of good cheer, I have overcome the world.",
    "Romans 8:38-39 - For I am persuaded that neither death nor life, nor angels nor principalities nor powers, nor things present nor things to come, nor height nor depth, nor any other created thing, shall be able to separate us from the love of God which is in Christ Jesus our Lord.",
    "2 Timothy 1:7 - For God has not given us a spirit of fear, but of power and of love and of a sound mind.",
    "Hebrews 13:8 - Jesus Christ is the same yesterday, today, and forever.",
    "1 Peter 5:6-7 - Therefore humble yourselves under the mighty hand of God, that He may exalt you in due time, casting all your care upon Him, for He cares for you.",
    "Revelation 21:4 - And God will wipe away every tear from their eyes; there shall be no more death, nor sorrow, nor crying. There shall be no more pain, for the former things have passed away.",
    "Psalm 19:14 - Let the words of my mouth and the meditation of my heart be acceptable in your sight, O Lord, my rock and my redeemer.",
    "Isaiah 41:10 - Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.",
    "Romans 15:13 - May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope.",
    "Psalm 37:4 - Delight yourself in the Lord, and he will give you the desires of your heart.",
    "Romans 12:2 - Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.",
    "Psalm 118:24 - This is the day that the Lord has made; let us rejoice and be glad in it.",
    "John 14:1 - Let not your hearts be troubled. Believe in God; believe also in me.",
    "Psalm 119:105 - Your word is a lamp to my feet and a light to my path.",
    "Isaiah 40:31 - But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.",
    "1 Corinthians 16:14 - Let all that you do be done in love.",
    "Psalm 136:1 - Give thanks to the Lord, for he is good, for his steadfast love endures forever.",
    "Colossians 3:23 - Whatever you do, work heartily, as for the Lord and not for men.",
    "Jeremiah 17:7 - Blessed is the man who trusts in the Lord, whose trust is the Lord.",
    "Psalm 27:1 - The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?",
    "James 1:5 - If any of you lacks wisdom, let him ask God, who gives generously to all without reproach, and it will be given him.",
    "Psalm 46:1 - God is our refuge and strength, a very present help in trouble.",
    "1 Thessalonians 5:16-18 - Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.",
    "Jeremiah 29:13 - You will seek me and find me, when you seek me with all your heart.",
    "Psalm 51:10 - Create in me a clean heart, O God, and renew a right spirit within me.",
    "Matthew 11:28 - Come to me, all who labor and are heavy laden, and I will give you rest.",
    "Isaiah 43:2 - When you pass through the waters, I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you.",
    "Proverbs 3:6 - In all your ways acknowledge him, and he will make straight your paths.",
    "Matthew 28:19-20 - Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all that I have commanded you. And behold, I am with you always, to the end of the age.",
    "Psalm 143:8 - Let me hear in the morning of your steadfast love, for in you I trust. Make me know the way I should go, for to you I lift up my soul.",
    "Luke 6:31 - And as you wish that others would do to you, do so to them.",
    "Isaiah 53:5 - But he was pierced for our transgressions; he was crushed for our iniquities; upon him was the chastisement that brought us peace, and with his wounds we are healed.",
    "Proverbs 16:3 - Commit your work to the Lord, and your plans will be established.",
    "Matthew 5:14 - You are the light of the world. A city set on a hill cannot be hidden.",
    "Psalm 34:8 - Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!",
    "John 14:15 - If you love me, you will keep my commandments.",
    "Psalm 91:1-2 - He who dwells in the shelter of the Most High will abide in the shadow of the Almighty. I will say to the Lord, 'My refuge and my fortress, my God, in whom I trust.'",
    "Romans 10:9 - If you confess with your mouth that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved.",
    "Philippians 2:3 - Do nothing from rivalry or conceit, but in humility count others more significant than yourselves.",
    "Psalm 121:1-2 - I lift up my eyes to the hills. From where does my help come? My help comes from the Lord, who made heaven and earth.",
    "John 10:10 - The thief comes only to steal and kill and destroy. I came that they may have life and have it abundantly.",
    "Romans 5:8 - But God shows his love for us in that while we were still sinners, Christ died for us.",
    "Psalm 100:4 - Enter his gates with thanksgiving, and his courts with praise! Give thanks to him; bless his name!",
    "Proverbs 17:17 - A friend loves at all times, and a brother is born for adversity.",
    "1 John 1:9 - If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.",
    "Psalm 103:1-2 - Bless the Lord, O my soul, and all that is within me, bless his holy name! Bless the Lord, O my soul, and forget not all his benefits.",
    "Matthew 5:44 - But I say to you, Love your enemies and pray for those who persecute you.",
    "Isaiah 26:3 - You keep him in perfect peace whose mind is stayed on you, because he trusts in you.",
    "Psalm 46:10 - Be still, and know that I am God. I will be exalted among the nations, I will be exalted in the earth!",
    "Romans 13:10 - Love does no wrong to a neighbor; therefore love is the fulfilling of the law.",
    "Jeremiah 32:27 - Behold, I am the Lord, the God of all flesh. Is anything too hard for me?",
    "Psalm 119:11 - I have stored up your word in my heart, that I might not sin against you.",
    "Matthew 22:37 - And he said to him, 'You shall love the Lord your God with all your heart and with all your soul and with all your mind.'",
    "Philippians 4:19 - And my God will supply every need of yours according to his riches in glory in Christ Jesus.",
    "Isaiah 40:8 - The grass withers, the flower fades, but the word of our God will stand forever.",
    "Psalm 139:23-24 - Search me, O God, and know my heart! Try me and know my thoughts! And see if there be any grievous way in me, and lead me in the way everlasting!",
    "Matthew 6:21 - For where your treasure is, there your heart will be also.",
    "Romans 14:11 - For it is written, 'As I live, says the Lord, every knee shall bow to me, and every tongue shall confess to God.'",
    "James 4:7-8 - Submit yourselves therefore to God. Resist the devil, and he will flee from you. Draw near to God, and he will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you double-minded.",
    "Psalm 119:105 - Your word is a lamp to my feet and a light to my path.",
    "Luke 12:15 - And he said to them, 'Take care, and be on your guard against all covetousness, for one's life does not consist in the abundance of his possessions.'",
    "Proverbs 22:6 - Train up a child in the way he should go; even when he is old he will not depart from it.",
    "John 14:21 - Whoever has my commandments and keeps them, he it is who loves me. And he who loves me will be loved by my Father, and I will love him and manifest myself to him.",
    "Psalm 37:23-24 - The steps of a man are established by the Lord, when he delights in his way; though he fall, he shall not be cast headlong, for the Lord upholds his hand.",
    "Romans 12:2 - Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.",
    "Philippians 1:6 - And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.",
    "Psalm 37:4 - Delight yourself in the Lord, and he will give you the desires of your heart.",
    "James 1:19 - Know this, my beloved brothers: let every person be quick to hear, slow to speak, slow to anger;",
    "Matthew 5:7 - Blessed are the merciful, for they shall receive mercy.",
    "Proverbs 3:5-6 - Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.",
    "Psalm 27:1 - The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?",
    "John 10:10 - The thief comes only to steal and kill and destroy. I came that they may have life and have it abundantly.",
    "Proverbs 16:3 - Commit your work to the Lord, and your plans will be established.",
    "2 Corinthians 5:17 - Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.",
    "Psalm 37:4 - Delight yourself in the Lord, and he will give you the desires of your heart.",
    "Jeremiah 29:13 - You will seek me and find me when you seek me with all your heart.",
    "Matthew 28:19-20 - Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all that I have commanded you. And behold, I am with you always, to the end of the age.",
    "Proverbs 3:6 - In all your ways acknowledge him, and he will make straight your paths.",
    "Psalm 91:1 - He who dwells in the shelter of the Most High will abide in the shadow of the Almighty.",
    "Philippians 4:19 - And my God will supply every need of yours according to his riches in glory in Christ Jesus.",
    "Isaiah 40:31 - But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.",
    "Psalm 37:23 - The steps of a man are established by the Lord, when he delights in his way.",
    "Proverbs 4:23 - Keep your heart with all vigilance, for from it flow the springs of life.",
    "Matthew 6:34 - Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.",
    "Romans 12:2 - Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.",
    "1 John 1:9 - If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.",
    "Psalm 103:12 - As far as the east is from the west, so far does he remove our transgressions from us.",
    "Galatians 5:16 - But I say, walk by the Spirit, and you will not gratify the desires of the flesh.",
    "Psalm 34:8 - Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!",
    "Colossians 3:23 - Whatever you do, work heartily, as for the Lord and not for men.",
    "Psalm 121:1-2 - I lift up my eyes to the hills. From where does my help come? My help comes from the Lord, who made heaven and earth.",
    "John 13:34-35 - A new commandment I give to you, that you love one another: just as I have loved you, you also are to love one another. By this all people will know that you are my disciples, if you have love for one another.",
    "Philippians 1:6 - And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ."

]
